# Generated by Django 5.2.2 on 2025-06-18 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id_negocio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('departamento', models.CharField(blank=True, choices=[('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Santa Cruz', 'Santa Cruz'), ('Oruro', 'Oruro'), ('Potosí', 'Potosí'), ('Tarija', 'Tarija'), ('Beni', 'Beni'), ('Pando', 'Pando'), ('Chuquisaca', 'Chuquisaca')], default='La Paz', max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('longitud', models.DecimalField(decimal_places=25, max_digits=30)),
                ('latitud', models.DecimalField(decimal_places=25, max_digits=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios/logos/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='negocios/fotos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'negocio',
            },
        ),
    ]
