# Generated by Django 5.2.2 on 2025-06-18 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.IntegerField()),
                ('max_reservas', models.IntegerField()),
                ('max_servicios', models.IntegerField()),
                ('max_horarios', models.IntegerField()),
                ('soporte_prioritario', models.BooleanField(default=False)),
                ('estadisticas_avanzadas', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'plan',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_proximo_pago', models.DateTimeField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='negocio.negocio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscripcion.plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripcion',
                'unique_together': {('negocio', 'plan')},
            },
        ),
    ]
