# Generated by Django 5.2.2 on 2025-06-18 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('rol', '0001_initial'),
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia_anios', models.IntegerField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
                ('rol', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rol.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
    ]
