# Generated by Django 5.2.2 on 2025-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(to='servicio.servicio'),
        ),
    ]
