# Generated by Django 5.2.2 on 2025-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_remove_reserva_servicio_reserva_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
